// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID                int64         `json:"id"`
	AccountID         sql.NullInt64 `json:"account_id"`
	RoleID            int64         `json:"role_id"`
	Email             string        `json:"email"`
	PasswordHash      string        `json:"password_hash"`
	PasswordChangedAt time.Time     `json:"password_changed_at"`
	Active            bool          `json:"active"`
	LoginAt           time.Time     `json:"login_at"`
	CreatedAt         time.Time     `json:"created_at"`
}
